version: '3'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mvc-app
        volumes:
            - ./app:/var/www/html
        ports:
            - "8080:80"
        tty: true
        networks:
            - mvc-network
        depends_on:
            - db

    db:
        build:
            context: ./docker/mysql
            dockerfile: Dockerfile
        container_name: mvc-db
        # restart: always
        tty: true
        ports:
            - "33062:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=mvc_php
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - mvc-network

    phpmyadmin:
        build:
            context: ./docker/phpmyadmin
            dockerfile: Dockerfile
        container_name: mvc-phpmyadmin
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - mvc-network
        depends_on:
            - db

networks:
    mvc-network:
        driver: bridge
    